### ISSUE TITLE
Added stops cause r5 to crash

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#133]
When you try to apply a modification with added stops, r5 crashes:
```
18:01:04.804 INFO (Scenario.java:53) Resolving modifications against TransportNetwork and sanity checking.

java.lang.IndexOutOfBoundsException: Index: 17302, Size: 17302

	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.conveyal.r5.streets.StreetRouter.route(StreetRouter.java:413)
	at com.conveyal.r5.transit.TransitLayer.buildOneStopTree(TransitLayer.java:396)
	at com.conveyal.r5.analyst.scenario.StopSpec.materializeOne(StopSpec.java:84)
	at com.conveyal.r5.analyst.scenario.StopSpec.resolve(StopSpec.java:53)
	at com.conveyal.r5.analyst.scenario.AddTrips.resolve(AddTrips.java:82)
	at com.conveyal.r5.analyst.scenario.Scenario.applyToTransportNetwork(Scenario.java:58)
	at com.conveyal.r5.analyst.scenario.AddTripsTest.testAddUnidirectionalTripWithAddedStops(AddTripsTest.java:269)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
```

**Comment by mattwigway** [comment]
There is a test that exercises this which is currently failing: `AddTripsTest::testUnidirectionalTripWithAddedStops`.

**Comment by abyrd** [comment]
Yeah I've got local changes to this, still working on it.
