### ISSUE TITLE
Point to point routing crashes with frequency routes

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#205]
Doing point-to-point routing on a bunch of feeds for Montréal, I get the following error:

```
[qtp1000611085-30] INFO com.conveyal.r5.profile.McRaptorSuboptimalPathProfileRouter - 8 patterns found near the destination
[qtp1000611085-30] INFO graphql.execution.ExecutionStrategy - Exception while fetching data
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.conveyal.r5.profile.McRaptorSuboptimalPathProfileRouter.doOneRound(McRaptorSuboptimalPathProfileRouter.java:404)
	at com.conveyal.r5.profile.McRaptorSuboptimalPathProfileRouter.route(McRaptorSuboptimalPathProfileRouter.java:181)
	at com.conveyal.r5.profile.McRaptorSuboptimalPathProfileRouter.getPaths(McRaptorSuboptimalPathProfileRouter.java:254)
	at com.conveyal.r5.point_to_point.builder.PointToPointQuery.getPlan(PointToPointQuery.java:115)
	at com.conveyal.r5.GraphQLSchema.lambda$new$233(GraphQLSchema.java:1530)

```

The final array dereference in expression `offsets.offsets.get(patIdx)[currentTrip][frequencyEntry]` runs off the end of the array because the index frequencyEntry equals 1, but the array has length 1.

This raises a larger question though: why are these routes being randomized at all? And why are they being randomized exactly once per minute in the departure time window? Does this give meaningful results?

**Comment by abyrd** [comment]
This appears to be a bug in the McRAPTOR suboptimal path finding code when searching for a tripSchedule to board on a frequency-based pattern. The index of the tripSchedule was never incremented, so tripSchedule 0 was always used, independent of which tripSchedule actually contained the frequency entry that was compatible with the specified departure time.

About scheduled being randomized (as mentioned in a previous comment) the point-to-point routing system does throw an unsupported operation exception when the network contains frequencies. The underlying routing does function, but it appears that the results are considered invalid due to this randomization problem.
