### ISSUE TITLE
Analysis worker: "pipe closed"

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#303]
When performing single point analysis, worker reports:

```
[pool-1-thread-1] ERROR com.conveyal.r5.analyst.cluster.AnalystWorker - Error writing travel time surface to broker

java.io.IOException: Pipe closed
at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:260)
at java.io.PipedInputStream.receive(PipedInputStream.java:226)
at java.io.PipedOutputStream.write(PipedOutputStream.java:149)
at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
at java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:145)
at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
at com.conveyal.r5.analyst.TravelTimeSurfaceComputer.write(TravelTimeSurfaceComputer.java:161)
at com.conveyal.r5.analyst.cluster.AnalystWorker.handleTravelTimeSurfaceRequest(AnalystWorker.java:534)
at com.conveyal.r5.analyst.cluster.AnalystWorker.handleOneRequest(AnalystWorker.java:414)
at com.conveyal.r5.analyst.cluster.AnalystWorker.lambda$null$6(AnalystWorker.java:671)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by abyrd** [comment]
We've also got HTTP failures on the worker:

```
Caused by: java.net.SocketException: Connection timed out (Write failed)
at java.net.SocketOutputStream.socketWrite0(Native Method)
at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:126)
at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:138)
at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:169)
at org.apache.http.impl.io.ChunkedOutputStream.flushCacheWithAppend(ChunkedOutputStream.java:123)
at org.apache.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:181)
at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:136)
at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:123)
at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:158)
at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:237)
at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:122)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
```

**Comment by abyrd** [comment]
Ah, but the worker had spent the previous 5 minutes linking a pointset and computing distance tables to all of Switzerland. This happened right after I switched to car routing, so it was relinking everything for the first time. Wondering if the problems are just due to the slowness of linking, or memory constraints causing GC as well.

**Comment by abyrd** [comment]
One observation that might impact how smoothly the system handles slow processes like linking:

Upon switching to driving mode, we see this is the worker logs:
```
[pool-1-thread-4] INFO com.conveyal.r5.analyst.cluster.AnalystWorker - Returning high-priority results for task 296426
[pool-1-thread-4] INFO com.conveyal.r5.streets.LinkedPointSet - Linking pointset to street network...
```

We appear to be fetching the pointset (triggering it to be linked when it isn't yet linked) after we begin returning the results. This means we might have a connection remaining open to the broker during the whole linking process, which explains various timeouts and glitches. We should call any potentially slow process (getting a pointset that might need to be linked) before we open a connection to the broker.

**Comment by abyrd** [comment]
Seeing this again, just after an NL worker spent half an hour making linkages. The worker remains essentially unusable for this period.
