### ISSUE TITLE
StopTime referencing non-existant Stop Causes NPE

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#400]
The pattern name generator assumes that all referenced stops exist. We should probably completely drop trips that visit non-existant stops.

```
370382 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: stop_times line 633, field 'stop_id': 4256
370382 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: stop_times line 634, field 'stop_id': 6601
370382 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: stop_times line 651, field 'stop_id': 6602
370382 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: stop_times line 652, field 'stop_id': 4257
370382 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: transfers line 0: Table is present in zip file, but it has no entries.
370382 [main] INFO com.conveyal.gtfs.GTFSFeed - Building stop to stop times index
370396 [main] INFO com.conveyal.gtfs.GTFSFeed - Building trips per service index
370398 [main] INFO com.conveyal.gtfs.GTFSFeed - Building services per date index
370506 [main] INFO com.conveyal.gtfs.GTFSFeed - Generating unique names for patterns
Disconnected from the target VM, address: '127.0.0.1:59881', transport: 'socket'
Exception in thread "main" java.lang.NullPointerException
	at com.conveyal.gtfs.GTFSFeed.lambda$namePatterns$15(GTFSFeed.java:568)
	at com.conveyal.gtfs.GTFSFeed$$Lambda$76/628164202.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.conveyal.gtfs.GTFSFeed.namePatterns(GTFSFeed.java:567)
	at com.conveyal.gtfs.GTFSFeed.findPatterns(GTFSFeed.java:529)
	at com.conveyal.r5.transit.TransitLayer.loadFromGtfs(TransitLayer.java:208)
	at com.conveyal.r5.transit.TransitLayer.loadFromGtfs(TransitLayer.java:163)
	at com.conveyal.r5.transit.TransportNetwork.fromFiles(TransportNetwork.java:205)
	at com.conveyal.r5.transit.TransportNetwork.fromFiles(TransportNetwork.java:241)
	at com.conveyal.r5.transit.TransportNetwork.fromDirectory(TransportNetwork.java:275)
	at com.conveyal.r5.point_to_point.PointToPointRouterServer.main(PointToPointRouterServer.java:73)
	at com.conveyal.r5.R5Main.main(R5Main.java:29)

```

**Comment by ansoncfit** [comment]
May be resolved by https://github.com/conveyal/r5/pull/724
