### ISSUE TITLE
Check walk and bike speeds to avoid divide by 0 errors

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#410]
If a user enters 0 for walk speed or bike speed, bad things happen (especially when running a regional analysis):

```
java.lang.ArithmeticException: / by zero
at com.conveyal.r5.profile.PerTargetPropagater.lambda$propagate$0(PerTargetPropagater.java:146)
at gnu.trove.map.hash.TIntIntHashMap.forEachEntry(TIntIntHashMap.java:422)
at com.conveyal.r5.profile.PerTargetPropagater.propagate(PerTargetPropagater.java:140)
at com.conveyal.r5.analyst.TravelTimeComputer.computeTravelTimes(TravelTimeComputer.java:313)
at com.conveyal.r5.analyst.cluster.AnalystWorker.handleOneRequest(AnalystWorker.java:382)
at com.conveyal.r5.analyst.cluster.AnalystWorker.lambda$null$0(AnalystWorker.java:283)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by ansoncfit** [comment]
R5 times out when walk speed = 0 and access mode = bike.
