### ISSUE TITLE
Cannot save TransportNetworks bigger than 2GB

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#440]
The ExpandingMMFBytez we use to save TransportNetworks uses 32-bit addressing and Java integers are always signed, which gives a maximum size of 2GB. This is a low-level limitation of the external FST library we’re using for serialization. 

I the library’s author in the past and he indicated that FST is mainly intended for small network messages, so serializing objects over 2GB is not a priority. The library does use 64-bit integers in many places for addressing, but some crucial size variables are 32-bit.

Analysis is resilient enough to function even when it can’t save the graph file, but then every worker rebuilds the network at every startup. We may be able to replace or fork the serialization library but that’s a major operation, not a simple change.

**Comment by abyrd** [comment]
The serialization library is https://github.com/RuedigerMoeller/fast-serialization

Relevant issues:
https://github.com/RuedigerMoeller/fast-serialization/issues/175
https://github.com/RuedigerMoeller/fast-serialization/issues/132
https://github.com/RuedigerMoeller/fast-serialization/issues/78
https://github.com/RuedigerMoeller/fast-serialization/issues/44

**Comment by abyrd** [comment]
The Kryo library has roughly similar performance to FST and may be more designed for serializing huge objects to/from disk file streams. I have tried it out in the past and found it to be less of a drop-in solution than FST, requiring more configuration and custom serializers. But it could work.

There will soon be a new major version 5 of Kryo, which will be API and output incompatible with v4:
https://groups.google.com/forum/#!msg/kryo-users/sBZ10dwrwFQ/hb6FF5ZXCQAJ

**Comment by abyrd** [comment]
Unfortunately Kryo 5 gives the following exception when serializing a Trove collection:
```
com.esotericsoftware.kryo.KryoException: java.lang.ArrayIndexOutOfBoundsException: 0
Serialization trace:
PUT_ALL_PROC (gnu.trove.map.hash.TIntObjectHashMap)
wrapped (com.conveyal.r5.util.TIntIntHashMultimap)
turnRestrictions (com.conveyal.r5.streets.EdgeStore)
edgeStore (com.conveyal.r5.streets.StreetLayer)
streetLayer (com.conveyal.r5.transit.TransportNetwork)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:92)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:543)
	at com.conveyal.r5.transit.TransportNetwork.write(TransportNetwork.java:99)
	at com.conveyal.r5.point_to_point.PointToPointRouterServer.main(PointToPointRouterServer.java:77)
	at com.conveyal.r5.R5Main.main(R5Main.java:29)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.esotericsoftware.kryo.util.Generics.pushTypeVariables(Generics.java:134)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.pushTypeVariables(FieldSerializer.java:135)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:102)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	... 17 more
```

**Comment by abyrd** [comment]
Switched to the last stable Cryo 4.0.2. This gives errors about classes not having no-arg constructors. Adding a no-arg constructor to StreetLayer, we then get the same error about anonymous classes inside Trove maps. It looks like we'll need to add no-op private no-arg constructors all over the code base, which I'm not thrilled about. We'll also need to make custom serializers for Trove classes among other things.

**Comment by abyrd** [comment]
After setting some custom serializers and instantiation strategies I'm now able to round-trip an entire TransportNetwork through Kryo. Using a custom serializer (rather than the stock serializers that defer to Serializable or Externalizable) on very common types has a strong effect on the serialization speed. To see the effects of my Kryo configuration, I overrode some methods in the ClassResolver to count serialized instances and report those counts with the associated serializers:

| 283672 | int[]               | IntArraySerializer       |
|--------|---------------------|--------------------------|
| 33138  | TripSchedule        | FieldSerializer          |
| 22524  | TIntArrayList       | TIntArrayListSerializer  |
| 13902  | String              | StringSerializer         |
| 8005   | TurnRestriction     | FieldSerializer          |
| 2038   | BitSet              | JavaSerializer           |
| 2036   | PickDropType        | EnumSerializer           |
| 1027   | ArrayList           | CollectionSerializer     |
| 1018   | TripPattern         | FieldSerializer          |
| 505    | LocalDate           | LocalDateSerializer      |
| 504    | CalendarDate        | FieldSerializer          |
| 242    | State               | FieldSerializer          |
| 98     | RouteInfo           | FieldSerializer          |
| 31     | HashMap             | MapSerializer            |
| 29     | Service             | FieldSerializer          |
| 17     | TIntObjectHashMap   | ExternalizableSerializer |
| 14     | ParkRideParking     | FieldSerializer          |
| 4      | String[]            | StringArraySerializer    |
| 3      | TransportNetwork    | FieldSerializer          |
| 3      | TByteArrayList      | FieldSerializer          |
| 2      | VertexStore         | FieldSerializer          |
| 2      | StreetLayer         | FieldSerializer          |
| 2      | TIntIntHashMultimap | FieldSerializer          |
| 2      | PickDropType[]      | ObjectArraySerializer    |
| 2      | Integer             | IntSerializer            |
| 1      | boolean             | BooleanSerializer        |
| 1      | URL                 | URLSerializer            |
| 1      | int                 | IntSerializer            |
| 1      | ZoneRegion          | ZoneIdSerializer         |
| 1      | TransitLayer        | FieldSerializer          |
| 1      | long[]              | LongArraySerializer      |
| 1      | Long                | LongSerializer           |
| 1      | Envelope            | FieldSerializer          |
| 1      | short[]             | ShortArraySerializer     |
| 1      | double              | DoubleSerializer         |
| 1      | EdgeStore           | FieldSerializer          |
| 1      | TShortArrayList     | FieldSerializer          |
| 1      | float[]             | FloatArraySerializer     |
| 1      | byte[]              | ByteArraySerializer      |
| 1      | float               | FloatSerializer          |
| 1      | TLongArrayList      | FieldSerializer          |
| 1      | StreetMode          | EnumSerializer           |
| 1      | char                | CharSerializer           |
| 1      | byte                | ByteSerializer           |
| 1      | void                | VoidSerializer           |
| 1      | long                | LongSerializer           |
| 1      | short               | ShortSerializer          |

(The text output was sorted as a spreadsheet and turned into a Markdown table using http://www.tablesgenerator.com/markdown_tables)

The configuration is as follows:

```
private static Kryo makeKryo () {
        Kryo kryo = new Kryo(new InstanceCountingClassResolver(), new MapReferenceResolver(), new DefaultStreamFactory());
        kryo.setRegistrationRequired(false);
        kryo.setReferences(true);
        kryo.register(TIntArrayList.class, new TIntArrayListSerializer());
        // Set default serializer for a whole hierarchy of Trove classes, which are Externalizable
        kryo.addDefaultSerializer(TIntHash.class, ExternalizableSerializer.class);
        // Default serialization of BitSets leaves them empty.
        // The BitSet serializer in magro/kryo-serializers naively writes out a dense stream of booleans.
        // BitSet's built-in Java serializer saves the internal bitfields, which is efficient.
        kryo.register(BitSet.class, new JavaSerializer());
       // Look for a zero-arg constructor, then fall back to the same strategy as Serializable
        kryo.setInstantiatorStrategy(new Kryo.DefaultInstantiatorStrategy(new SerializingInstantiatorStrategy()));
        return kryo;
    }
```
