### ISSUE TITLE
Regional analysis stalls with unrecognized route_type

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#443]
Using GTFS where all routes have route_type = 1501,

```
3732860 [pool-1-thread-10] ERROR com.conveyal.r5.analyst.cluster.AnalystWorker - An error occurred while routing: Taxi service not supported1501
13:23:06
java.lang.IllegalArgumentException: Taxi service not supported1501 at com.conveyal.r5.transit.TransitLayer.getTransitModes(TransitLayer.java:673) at com.conveyal.r5.profile.FastRaptorWorker.prefilterPatterns(FastRaptorWorker.java:223) at com.conveyal.r5.profile.FastRaptorWorker.route(FastRaptorWorker.java:162) at com.conveyal.r5.analyst.TravelTimeComputer.computeTravelTimes(TravelTimeComputer.
java.lang.IllegalArgumentException: Taxi service not supported1501
at com.conveyal.r5.transit.TransitLayer.getTransitModes(TransitLayer.java:673)
at com.conveyal.r5.profile.FastRaptorWorker.prefilterPatterns(FastRaptorWorker.java:223)
at com.conveyal.r5.profile.FastRaptorWorker.route(FastRaptorWorker.java:162)
at com.conveyal.r5.analyst.TravelTimeComputer.computeTravelTimes(TravelTimeComputer.java:215)
at com.conveyal.r5.analyst.cluster.AnalystWorker.handleOneRequest(AnalystWorker.java:459)
at com.conveyal.r5.analyst.cluster.AnalystWorker.lambda$run$0(AnalystWorker.java:372)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
13:23:06
3732860 [pool-1-thread-10] WARN com.conveyal.r5.analyst.cluster.AnalystWorker - Errors while completing task:
3732860 [pool-1-thread-10] WARN com.conveyal.r5.analyst.cluster.AnalystWorker - Errors while completing task:
13:23:06
[com.conveyal.r5.analyst.error.TaskError@150916fe]
[com.conveyal.r5.analyst.error.TaskError@150916fe]
```

Interestingly, in a regional analysis the worker successfully completed 82524 / 97552.  But now it will just be kept alive as the broker re-delivers the same incomplete tasks.

**Comment by ansoncfit** [comment]
Closing, given that https://github.com/conveyal/analysis-ui/issues/684 makes this much less common, and #334 should fix it.
