### ISSUE TITLE
Adjust dwell time modification triggers NPE

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#456]
By default, an adjust dwell time modification is applied to all stops in selected route/patterns.  The UI shows all stops selected, and R5 specifies:
```
    /** Stops at which to change the dwell times. If not specified, all dwell times will be changed. */
    public Set<String> stops;
```

But analyzing a scenario with such a modification triggers
```
null java.lang.NullPointerException at java.util.Arrays.stream(Arrays.java:5004) at com.conveyal.taui.models.Modification.feedScopeIds(Modification.java:44) at com.conveyal.taui.models.AdjustDwellTime.toR5(AdjustDwellTime.java:36) at com.conveyal.taui.models.AdjustDwellTime.toR5(AdjustDwellTime.java:6) at 
```

As a workaround, users can explicitly select all stops on the desired route/patterns.

**Comment by abyrd** [comment]
Actually `com.conveyal.taui.models.Modification.feedScopeIds` is in analysis-backend. @trevorgerhardt applied a fix for the NPE itself in https://github.com/conveyal/analysis-backend/commit/f154b3c0b8a5e4ff61243f6a880e67b8db710e86#diff-a37c929fdad51790c339975c3a3848f4 

However, now if no stops are selected, it fails in a different way: R5 makes a distinction between null sets and empty sets. If no set is provided (null) it matches everything; if a set is provided those items must be matched, and if it's an empty set it matches nothing.

We can debate whether null collections should be normalized to empty collections, but null collections currently do have significance throughout the R5 scenario code. One change here in com/conveyal/taui/models/Modification.java, the code that transforms backend modifications into R5 modifications, may be causing several kinds of modifications to silently have no effect, we won’t know unless we sift through the code or test each combination of present/missing lists of routes, trips, stops etc.

 I think the safer quick fix is `if (ids == null) return null` i.e. return the null set instead of the empty set, preserving null collections found in the Mongo DB. I’m pretty sure R5 will work correctly in that case.
