### ISSUE TITLE
Loader considers extended route types to be errors.

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#476]
There is a GTFS extension allowing extended route types (hierarchical transit mode IDs). The 2019 Swiss GTFS uses these codes, and R5 doesn't understand them.

```
11:32:35
167424 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: routes line 539: Number 700.0 outside of acceptable range [0.0,7.0].
11:32:35
167424 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: routes line 540: Number 700.0 outside of acceptable range [0.0,7.0].
11:32:35
167424 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: routes line 541: Number 1400.0 outside of acceptable range [0.0,7.0].
11:32:35
167424 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: routes line 542: Number 1400.0 outside of acceptable range [0.0,7.0].
11:32:35
167425 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: routes line 543: Number 1400.0 outside of acceptable range [0.0,7.0].
11:32:35
167425 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: routes line 544: Number 1400.0 outside of acceptable range [0.0,7.0].
11:32:35
167425 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: routes line 545: Number 106.0 outside of acceptable range [0.0,7.0].
11:32:35
167425 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: routes line 546: Number 1000.0 outside of acceptable range [0.0,7.0].
11:32:35
167425 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: routes line 547: Number 700.0 outside of acceptable range [0.0,7.0].
11:32:35
167425 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: routes line 548: Number 1501.0 outside of acceptable range [0.0,7.0].
11:32:35
167425 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: routes line 549: Number 700.0 outside of acceptable range [0.0,7.0].
```

Google apparently accepts these codes, so some GTFS producers use them heavily.
https://developers.google.com/transit/gtfs/reference/extended-route-types

OTP supports them to a limited extent by mapping whole swaths of numbers to the 7 basic GTFS modes.

The method checkRangeInclusive that's detecting these "errors" does not reject the route entity though. The route is still saved, but with a mode code that may cause it to never be used in routing.

**Comment by abyrd** [comment]
This happens while building a network. The whole build operation fails with this exception:
```
java.lang.NullPointerException
at org.mapdb.BTreeMap.get(BTreeMap.java:593)
at org.mapdb.BTreeMap.get(BTreeMap.java:589)
at com.conveyal.r5.transit.TransitLayer.loadFromGtfs(TransitLayer.java:279)
at com.conveyal.r5.transit.TransitLayer.loadFromGtfs(TransitLayer.java:163)
```

This might be due to all route entities being rejected due to "out of range" mode codes. If so, this is a bad failure mode. It's not at all clear that it's caused by the out of range values.

**Comment by abyrd** [comment]
This should not affect routing. com.conveyal.r5.transit.TransitLayer#getTransitModes considers all the extended route types and maps them to known modes. So we just need to make the range checking in gtfs-lib less restrictive.

**Comment by ansoncfit** [comment]
See also https://github.com/conveyal/r5/issues/443

**Comment by abyrd** [comment]
This does affect routing with Swiss GTFS that includes taxi services. Although many codes are understood, R5 rejects the "taxi" mode:

```
Taxi service not supported1501 java.lang.IllegalArgumentException: Taxi service not supported1501 at com.conveyal.r5.transit.TransitLayer.getTransitModes(TransitLayer.java:688) at com.conveyal.r5.profile.FastRaptorWorker.prefilterPatterns(FastRaptorWorker.java:223) at com.conveyal.r5.profile.FastRaptorWorker.route(FastRaptorWorker.java:162) at com.conveyal.r5.analyst.TravelTimeComputer.computeTravelTimes(TravelTimeComputer.java:233) at com.conveyal.r5.analyst.cluster.AnalystWorker.handleOneSinglePointTask(AnalystWorker.java:415) at com.conveyal.r5.analyst.cluster.AnalysisWorkerController.handleSinglePoint(AnalysisWorkerController.java:45) at spark.RouteImpl$1.handle(RouteImpl.java:72) at spark.http.matching.Routes.execute(Routes.java:61) at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130) at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) at org.eclipse.jetty.server.Server.handle(Server.java:530) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708) at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626) at java.lang.Thread.run(Thread.java:748)
```

Again, see also #443.

**Comment by bobobo1618** [comment]
Could this be addressed by filtering out these routes in `loadFromGtfs`? I'd argue that if we know `getTransitModes` is going to throw an exception (which we can test when we load the route), we should log a warning and omit the route from the graph.

**Comment by trevorgerhardt** [comment]
Did #697 fully address this? Can this issue now be closed? @abyrd @ansoncfit
