### ISSUE TITLE
Null pointer exception while building Swiss network

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#477]
While building a network for 2019 Swiss GTFS, the whole build operation fails with this exception:
```
java.lang.NullPointerException
at org.mapdb.BTreeMap.get(BTreeMap.java:593)
at org.mapdb.BTreeMap.get(BTreeMap.java:589)
at com.conveyal.r5.transit.TransitLayer.loadFromGtfs(TransitLayer.java:279)
at com.conveyal.r5.transit.TransitLayer.loadFromGtfs(TransitLayer.java:163)
```

**Comment by abyrd** [comment]
Line 593 of BTreeMap is `if(key==null) throw new NullPointerException();` so the key is null.
Line 279 of TransitLayer is `String patternId = gtfs.tripPatternMap.get(tripId);` so the null key is the tripId. There is apparently a trip in the GTFS that has a null tripId.

**Comment by abyrd** [comment]
I may have been looking at a different version of the gtfs-lib code than is running on Analysis production. Running locally, this Swiss feed also throws a NPE but at a different line: `RouteInfo ri = new RouteInfo(route, gtfs.agency.get(route.agency_id));`

This does assume that every route has an agency ID which is not required by the spec.
