### ISSUE TITLE
Worker does not consider shutting down if backend is unreachable

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#542]
```
org.apache.http.conn.HttpHostConnectException: Connect to 10.0.0.160:7070 [/10.0.0.160] failed: Connection refused (Connection refused)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
at com.conveyal.r5.analyst.cluster.AnalystWorker.getSomeWork(AnalystWorker.java:601)
at com.conveyal.r5.analyst.cluster.AnalystWorker.run(AnalystWorker.java:352)
at com.conveyal.r5.analyst.cluster.AnalystWorker.main(AnalystWorker.java:681)
at com.conveyal.r5.R5Main.main(R5Main.java:30)
```

**Comment by ansoncfit** [comment]
It appears the above excerpt from a worker log is no the problem -- getSomeWork should return null after the polling exception, so considerShuttingDown is called.  But there seems to be a hole in the logic of calculating shutdown and preloading.

**Comment by ansoncfit** [comment]
Observed on production: a user started a regional analysis for a large region with a sparse network. The broker started ~170 workers, based on the number of origins. The previously-started single-point worker was handling ~2000 tasks per minute. All tasks were completed by the time the final ~100 workers came online, so they received no work when polling. These workers will stay alive doing nothing for `PRELOAD_KEEPALIVE_MINUTES = 90`.  A few responses:

1. Revise the shutdown logic so PRELOAD_KEEPALIVE is used more selectively
1. Shut down workers after a few minutes if they never receive any work.
1. Introduce additional heuristics (e.g. accounting for the number of stops, whether or not transit is used, etc.) into the broker's calculation of number of workers to start, beyond simply the number of origins.

**Comment by abyrd** [comment]
We saw this happening again recently, on a run by @ansoncfit and another one I did. With certain quantities of origins, all the tasks can be handed out to workers before some of them get any. The boolean `inPreload` remains true until the worker handles a task - this is not correct, it should be set to false and the shutdown duration set as soon as preloading finishes, whether or not the worker gets any tasks. I will look into this fix.

Additionally it's kind of useless for the workers to build a large network (preload) if they're never going to receive any work. But this may be an edge case and not worth special logic for actively shutting off workers.

**Comment by abyrd** [comment]
I have been diving into this more while working on #664. The current auto-shutdown behavior is not easy to infer from the code. Our workers start up with the shutdown timer in a "preload" (90-minute keepalive) stage independent of whether they are actually preloading a network (and preparing any linkages etc.) - network preparation only begins the first time they receive a regional or single point task. The adjustShutdownClock() calls are situated such that the shutdown timer exits this preload mode exactly once and never re-enters it, once all network preparation is finished (single point) or once the network is ready but before the distance tables and linkages are necessarily ready (regional).

In addition to the problem described in this issue (worker never receives tasks and is stays in 90-minute preload mode), there are several other edge cases and transitions that don't seem to be covered. 

A worker that receives regional tasks at startup and needs to perform some heavy work (e.g. a nationwide bike linkage and egress tables) will switch out of preload mode as soon as the network is loaded, switching to a 5-minute keepalive, before the heavy work (which can take many minutes) is initiated. Nonetheless it does not shut down because of the way the work queue blocks, preventing the worker polling block which also contains the shutdown check. This is not a good system as it relies on complex interactions between timeouts and polling loops that stall until more work is needed, so its intended behavior and mechanism of action are not obvious.

Also consider behavior when a worker is finishing one regional analysis and begins working on tasks from another analysis for a different scenario. It seems possible for the worker to call `considerShuttingDown()` during network preparation taking more than 5 minutes, and shut down before tasks are handled.

The system also does not seem robust against regional workers getting jammed in the network loading / linking / egress tables stages. For reasons described above, it appears that this would prevent the shutdown check from ever running.

In practice we rarely have noteworthy problems with auto-shutdown, but there is the occasional long-lived idle worker, regional tasks that need to be retried etc. and it's not easy to validate the correctness of the existing code for all cases. I'm rewriting this to make the assumptions and state more obvious, first replicating existing behavior but with hopes of making it more closely match expectations. This fits in well with making the shutdown check a regularly recurring PeriodicTask (eventually along with the worker polling itself).
