### ISSUE TITLE
Network building failure when GTFS feed contains pattern with only one stop

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#579]
Recently seen in the log of R5 `v4.8.0` worker, with what I believe was a "cropped" GTFS feed:
```
java.lang.NullPointerException
        at com.conveyal.gtfs.util.GeometryUtil.toLegacyLineString(GeometryUtil.java:25)
        at com.conveyal.gtfs.model.Pattern.<init>(Pattern.java:52)
        at com.conveyal.gtfs.GTFSFeed.lambda$findPatterns$4(GTFSFeed.java:475)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at com.google.common.collect.CollectSpliterators$1.lambda$forEachRemaining$1(CollectSpliterators.java:120)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
        at com.google.common.collect.CollectSpliterators$1.forEachRemaining(CollectSpliterators.java:120)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.conveyal.gtfs.GTFSFeed.findPatterns(GTFSFeed.java:476)
        at com.conveyal.r5.transit.TransitLayer.loadFromGtfs(TransitLayer.java:229)
        at com.conveyal.r5.transit.TransitLayer.loadFromGtfs(TransitLayer.java:181)
```
The trip geometry value passed to `toLegacyLinestring` will indeed be `null` if a trip does not have a shape specified in GTFS and has only one stop.  See:
https://github.com/conveyal/gtfs-lib/blob/3.0.x-maintenance/src/main/java/com/conveyal/gtfs/GTFSFeed.java#L623

The `toLegacyLinestring` method could instead return `null` if called with a `null` lineString parameter. 

We could also consider discarding such trips entirely when processing feeds, as they will never be used in routing.

Last, the stack trace above doesn't make it to the UI interface (see also #334).  Instead, the following error bubbles up:
```
java.lang.NullPointerException
        at com.conveyal.r5.transit.TransportNetworkCache.getNetworkForScenario(TransportNetworkCache.java:133)
        at com.conveyal.r5.analyst.NetworkPreloader.buildValue(NetworkPreloader.java:96)
        at com.conveyal.r5.analyst.NetworkPreloader.buildValue(NetworkPreloader.java:72)
        at com.conveyal.r5.util.AsyncLoader.lambda$get$0(AsyncLoader.java:122)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by abyrd** [comment]
In addition to the patch to gtfs-lib to tolerate null parameter values, we will also change R5 to drop one-stop patterns. This is safer because other code (e.g. code that iterates over stops in a trip) may assume patterns always contain at least two stops.

**Comment by ansoncfit** [comment]
Comment added at https://github.com/conveyal/r5/pull/869/files#diff-7e730d41af893ba6dbd9843026f07ebf1cf028c72eec7140cb51c9106f4d4fbcR594-R595
