### ISSUE TITLE
Report invalid GTFS to UI

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#624]
I am uploading a ZIP of 18 GTFS feeds and OSM data. The upload never seems to complete (based on the UI spinner). Looking at the server logs, I see that the GTFS feed is missing all required tables.

Oddly, it also reports that the feed does not contain a feed ID and it's using the file name 1b376653-c553-4d28-a752-3753d607952c. This ZIP file does not contain any file by that name, all GTFS files have been given the names of their respective agencies.

```
06:50:48.916 [Thread-16] INFO  c.conveyal.gtfs.model.Entity$Loader - Table feed_info was missing but it is not required.
06:50:48.916 [Thread-16] INFO  com.conveyal.gtfs.GTFSFeed - Feed ID is undefined, pester maintainers to include a feed ID. Using file name 1b376653-c553-4d28-a752-3753d607952c.
06:50:48.916 [Thread-16] INFO  c.conveyal.gtfs.model.Entity$Loader - Table calendar_dates was missing but it is not required.
06:50:48.916 [Thread-16] INFO  c.conveyal.gtfs.model.Entity$Loader - Table fare_attributes was missing but it is not required.
06:50:48.916 [Thread-16] INFO  c.conveyal.gtfs.model.Entity$Loader - Table fare_rules was missing but it is not required.
06:50:48.916 [Thread-16] INFO  c.conveyal.gtfs.model.Entity$Loader - Table shapes was missing but it is not required.
06:50:48.917 [Thread-16] INFO  c.conveyal.gtfs.model.Entity$Loader - Table transfers was missing but it is not required.
06:50:48.917 [Thread-16] INFO  c.conveyal.gtfs.model.Entity$Loader - Table frequencies was missing but it is not required.
06:50:48.917 [Thread-16] INFO  com.conveyal.gtfs.GTFSFeed - 6 errors
06:50:48.917 [Thread-16] INFO  com.conveyal.gtfs.GTFSFeed - GTFSError: agency line 0: This table is required by the GTFS specification but is missing.
06:50:48.917 [Thread-16] INFO  com.conveyal.gtfs.GTFSFeed - GTFSError: calendar line 0: This table is required by the GTFS specification but is missing.
06:50:48.917 [Thread-16] INFO  com.conveyal.gtfs.GTFSFeed - GTFSError: routes line 0: This table is required by the GTFS specification but is missing.
06:50:48.917 [Thread-16] INFO  com.conveyal.gtfs.GTFSFeed - GTFSError: stop_times line 0: This table is required by the GTFS specification but is missing.
06:50:48.917 [Thread-16] INFO  com.conveyal.gtfs.GTFSFeed - GTFSError: stops line 0: This table is required by the GTFS specification but is missing.
06:50:48.917 [Thread-16] INFO  com.conveyal.gtfs.GTFSFeed - GTFSError: trips line 0: This table is required by the GTFS specification but is missing.
06:50:48.917 [Thread-16] INFO  com.conveyal.gtfs.GTFSFeed - Building stop to stop times index
06:50:48.917 [Thread-16] INFO  com.conveyal.gtfs.GTFSFeed - Building trips per service index
06:50:48.917 [Thread-16] INFO  com.conveyal.gtfs.GTFSFeed - Building services per date index
06:50:48.917 [Thread-16] INFO  com.conveyal.gtfs.GTFSFeed - Generating unique names for patterns
06:50:48.917 [Thread-16] INFO  com.conveyal.gtfs.GTFSFeed - Total patterns: 0
06:50:49.029 [Thread-16] INFO  com.conveyal.gtfs.GTFSCache - Writing feed to s3 cache
06:50:51.322 [Thread-16] INFO  com.conveyal.gtfs.GTFSCache - Zip file written.
06:50:51.500 [Thread-16] INFO  com.conveyal.gtfs.GTFSCache - db files written.
Exception in thread "Thread-16" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
        at gnu.trove.list.array.TDoubleArrayList.get(TDoubleArrayList.java:281)
        at com.conveyal.taui.controllers.BundleController.lambda$create$10(BundleController.java:157)
        at java.lang.Thread.run(Unknown Source)
```

Finally finding the geographic center fails because of course the feed has no stops. It seems clear that the server is attempting to interpret some ZIP file as a GTFS feed, when the file is not really a GTFS feed. But I unzipped the file I uploaded and unzipped all the GTFS files it contains, and they all look like valid GTFS with routes, stops etc.

The simplest explanation is that the server is interpreting my ZIP of 18xGTFS+OSM as a single GTFS feed, which would lead to exactly these errors. I see that my 117MB archive appears in the analyst disk cache prefixed with the same UUID that the logs report as the corrupt GTFS's file name.

**Comment by ansoncfit** [comment]
https://github.com/conveyal/r5/pull/713 closes.
