### ISSUE TITLE
Exception, apparently while generating pattern names

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#628]
This exception is likely caused by the bad stopId references that are also reported:

```
07:04:21.388 [Thread-74] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table feed_info from feed_info.txt
07:04:21.388 [Thread-74] INFO  com.conveyal.gtfs.GTFSFeed - Feed ID is 'GVMB2030'.
07:04:21.388 [Thread-74] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table agency from agency.txt
07:04:21.388 [Thread-74] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table calendar from calendar.txt
07:04:21.388 [Thread-74] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table calendar_dates from calendar_dates.txt
07:04:21.388 [Thread-74] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table fare_attributes from fare_attributes.txt
07:04:21.388 [Thread-74] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table fare_rules from fare_rules.txt
07:04:21.388 [Thread-74] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table routes from routes.txt
07:04:21.389 [Thread-74] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table shapes from shapes.txt
07:04:21.629 [Thread-74] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table stops from stops.txt
07:04:21.644 [Thread-74] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table transfers from transfers.txt
07:04:21.644 [Thread-74] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table trips from trips.txt
07:04:21.646 [Thread-74] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table frequencies from frequencies.txt
07:04:21.657 [Thread-74] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table stop_times from stop_times.txt
07:04:21.677 [Thread-74] INFO  com.conveyal.gtfs.GTFSFeed - 9 errors
07:04:21.677 [Thread-74] INFO  com.conveyal.gtfs.GTFSFeed - GTFSError: agency line 1, field 'agency_url': No value supplied for a required column.
07:04:21.677 [Thread-74] INFO  com.conveyal.gtfs.GTFSFeed - GTFSError: calendar_dates line 0: Table is present in zip file, but it has no entries.
07:04:21.677 [Thread-74] INFO  com.conveyal.gtfs.GTFSFeed - GTFSError: fare_attributes line 0: Table is present in zip file, but it has no entries.
07:04:21.677 [Thread-74] INFO  com.conveyal.gtfs.GTFSFeed - GTFSError: fare_rules line 0: Table is present in zip file, but it has no entries.
07:04:21.677 [Thread-74] INFO  com.conveyal.gtfs.GTFSFeed - GTFSError: stop_times line 633, field 'stop_id': 4256
07:04:21.677 [Thread-74] INFO  com.conveyal.gtfs.GTFSFeed - GTFSError: stop_times line 634, field 'stop_id': 6601
07:04:21.677 [Thread-74] INFO  com.conveyal.gtfs.GTFSFeed - GTFSError: stop_times line 651, field 'stop_id': 6602
07:04:21.677 [Thread-74] INFO  com.conveyal.gtfs.GTFSFeed - GTFSError: stop_times line 652, field 'stop_id': 4257
07:04:21.677 [Thread-74] INFO  com.conveyal.gtfs.GTFSFeed - GTFSError: transfers line 0: Table is present in zip file, but it has no entries.
07:04:21.677 [Thread-74] INFO  com.conveyal.gtfs.GTFSFeed - Building stop to stop times index
07:04:21.683 [Thread-74] INFO  com.conveyal.gtfs.GTFSFeed - Building trips per service index
07:04:21.684 [Thread-74] INFO  com.conveyal.gtfs.GTFSFeed - Building services per date index
07:04:21.774 [Thread-74] INFO  com.conveyal.gtfs.GTFSFeed - Generating unique names for patterns
07:04:21.777 [Thread-74] INFO  c.conveyal.taui.persistence.MongoMap - Bundle SBBF4B CH2017 GVMB2030 (5aab6b0a896fd05db5c4612f) SBBF4B CH2017 GVMB2030 updated by abyrd+sbb@conveyal.com (sbb)
Exception in thread "Thread-74" com.conveyal.taui.AnalysisServerException
	at com.conveyal.taui.AnalysisServerException.Unknown(AnalysisServerException.java:77)
	at com.conveyal.taui.controllers.BundleController.lambda$null$1(BundleController.java:143)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.conveyal.taui.controllers.BundleController.lambda$create$5(BundleController.java:146)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ansoncfit** [comment]
May be resolved by https://github.com/conveyal/r5/pull/724
