### ISSUE TITLE
NPE when returning mysterious GraphQL error

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#629]
Right after uploading a huge GTFS feed (NL), after server logs show that it has been uploaded to S3, an attempt to view a project using that feed results in an error: 

```
08:11:36.176 [qtp1776974032-14] INFO  graphql.execution.ExecutionStrategy - Exception while fetching data
java.lang.NullPointerException: null
        at com.conveyal.taui.controllers.GraphQLController.fetchFeeds(GraphQLController.java:157) [analyst-dev-b262591.jar:1.1]
        at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:41) [analyst-dev-b262591.jar:1.1]
        at graphql.execution.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:18) [analyst-dev-b262591.jar:1.1]
        at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:89) [analyst-dev-b262591.jar:1.1]
        at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:128) [analyst-dev-b262591.jar:1.1]
        at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:97) [analyst-dev-b262591.jar:1.1]
        at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:62) [analyst-dev-b262591.jar:1.1]
        at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:47) [analyst-dev-b262591.jar:1.1]
        at graphql.execution.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:18) [analyst-dev-b262591.jar:1.1]
        at graphql.execution.Execution.executeOperation(Execution.java:60) [analyst-dev-b262591.jar:1.1]
        at graphql.execution.Execution.execute(Execution.java:33) [analyst-dev-b262591.jar:1.1]
        at graphql.GraphQL.execute(GraphQL.java:78) [analyst-dev-b262591.jar:1.1]
        at com.conveyal.taui.controllers.GraphQLController.handleQuery(GraphQLController.java:63) [analyst-dev-b262591.jar:1.1]
        at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) ~[analyst-dev-b262591.jar:1.1]
        at spark.http.matching.Routes.execute(Routes.java:61) ~[analyst-dev-b262591.jar:1.1]
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130) ~[analyst-dev-b262591.jar:1.1]
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) ~[analyst-dev-b262591.jar:1.1]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568) ~[analyst-dev-b262591.jar:1.1]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[analyst-dev-b262591.jar:1.1]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[analyst-dev-b262591.jar:1.1]
        at org.eclipse.jetty.server.Server.handle(Server.java:564) ~[analyst-dev-b262591.jar:1.1]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317) ~[analyst-dev-b262591.jar:1.1]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) ~[analyst-dev-b262591.jar:1.1]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) ~[analyst-dev-b262591.jar:1.1]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) ~[analyst-dev-b262591.jar:1.1]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) ~[analyst-dev-b262591.jar:1.1]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673) ~[analyst-dev-b262591.jar:1.1]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591) ~[analyst-dev-b262591.jar:1.1]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
```

Then immediately afterward (with no mention of "caused by", this appears to be a separate exception) we also see:

```
08:11:36.177 [qtp1776974032-14] ERROR com.conveyal.taui.AnalysisServer - GRAPHQL  Exception while fetching data: java.lang.NullPointerException -> GET /api/graphql by abyrd@conveyal.com of conveyal [ http://tkp.to/gOt3zn4 ]
08:11:36.177 [qtp1776974032-14] ERROR com.conveyal.taui.AnalysisServer - com.conveyal.taui.AnalysisServerException
        at com.conveyal.taui.AnalysisServerException.GraphQL(AnalysisServerException.java:55)
        at com.conveyal.taui.controllers.GraphQLController.handleQuery(GraphQLController.java:68)
        at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:564)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
        at java.lang.Thread.run(Thread.java:748)
```

The first stacktrace lines of this second exception are hard to interpret - is the reported line number due to the exception being constructed on that line? If so these exception factory methods are hiding the original source of the exception (though it's probably the exception logged just above). We should change this.

After a while, for no reason apparent from the logs, the GraphQL requests just start working with no exceptions. This is the kind of delayed mystery behavior we have to eliminate.

**Comment by ansoncfit** [comment]
https://github.com/conveyal/r5/pull/742 eliminated our use of GraphQL.
