### ISSUE TITLE
Error for building 'big' network with germany-latest.osm.pbf  (seemingly caused by turn-restrictions)

### ISSUE THREAD

**Issue by SRN1973** [conveyal/r5#681]
I realized that r5r  that builds on r5 does not write back a calculated network.dat / respectively fails in the network building process when the input files cover a whole country. (If I try the same for a small subset e.g. the city of Hamburg than r5r works as described and expected).

Trying to isolate the error, I got following answer from the r5r programmers which solved the problem for me (nevertheless I feel that it schould be corrected in r5): 

"This is definitely an upstream bug in R5, and it has to do with turn restrictions, If you don't care about turn restrictions (which really only matter for driving, and to a lesser extent biking, but you can always walk your bike), you can use osmconvert with the --drop-relations option to remove them from your PBF. Then R5R should build the network, albeit without information on turn restrictions."

By the way I encounter a similar error when I try to build the Graph for the newer versions of the Open Trip Planner, too (as such I suspect it might be the same cause)

OPERATING SYSTEM:

Ubuntu 20.04.1 LTS
RAM: 1 TB
120 cernels

INPUT FILES:

germany-latest-osm.pbf (https://download.geofabrik.de/europe/germany-latest.osm.pbf)
[I already tried several dumps form different dates of the germany-latest-osm.pbf]
-GTFS files (whole public transport for Germany):
https://download.gtfs.de/germany/fv_free/latest.zip
https://download.gtfs.de/germany/nv_free/latest.zip
https://download.gtfs.de/germany/rv_free/latest.zip

COMMAND TO BUILD AND SAVE THE GRAPH:

java -Xmx500g -jar /usr/local/lib/R/site-library/r5r/jar/r5-v6.0.1-2-gf44e585-all.jar point --build

ERROR MESSAGE:
...
16:17:11.702 [main] WARN com.conveyal.r5.streets.StreetLayer - Did not find from/to edges for restriction 4429939, skipping
16:17:11.702 [main] WARN com.conveyal.r5.streets.StreetLayer - Did not find from/to edges for restriction 4429940, skipping
16:17:11.702 [main] WARN com.conveyal.r5.streets.StreetLayer - Did not find from/to edges for restriction 4429941, skipping
16:17:11.702 [main] WARN com.conveyal.r5.streets.StreetLayer - Did not find from/to edges for restriction 4429942, skipping
16:17:11.777 [main] ERROR com.conveyal.r5.streets.StreetLayer - Invalid turn restriction 4437683, does not have from, to and via, skipping
16:17:11.780 [main] ERROR com.conveyal.r5.streets.StreetLayer - Turn restriction 4437852 has multiple 'from' members, skipping.
16:17:11.780 [main] ERROR com.conveyal.r5.streets.StreetLayer - Turn restriction 4437855 has multiple 'from' members, skipping.
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 17384613
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
at java.base/java.util.Objects.checkIndex(Objects.java:372)
at java.base/java.util.ArrayList.get(ArrayList.java:459)
at com.conveyal.r5.streets.StreetLayer.applyTurnRestriction(StreetLayer.java:896)
at com.conveyal.r5.streets.StreetLayer.lambda$loadFromOsm$1(StreetLayer.java:374)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
at com.conveyal.r5.streets.StreetLayer.loadFromOsm(StreetLayer.java:374)
at com.conveyal.r5.streets.StreetLayer.loadFromOsm(StreetLayer.java:205)
at com.conveyal.r5.transit.TransportNetwork.fromFiles(TransportNetwork.java:142)
at com.conveyal.r5.transit.TransportNetwork.fromFiles(TransportNetwork.java:201)
at com.conveyal.r5.transit.TransportNetwork.fromDirectory(TransportNetwork.java:235)
at com.conveyal.r5.point_to_point.PointToPointRouterServer.main(PointToPointRouterServer.java:92)
at com.conveyal.r5.R5Main.main(R5Main.java:32)

**Comment by abyrd** [comment]
Thanks for the report @SRN1973, hope to look into this soon.

**Comment by SRN1973** [comment]
...The above described problem still persits. I am still unable to build the network with tha latest germany-latest-osm.pbf (https://download.geofabrik.de/europe/germany-latest.osm.pbf) without removing the turn restrictions prior to the network building process. I think this is a major issu as this prevents to properly use any applications building on R5 therefore I would be very pleased if you would address the problem at last .... it was reportet more than one year ago now and I can not see any improvement yet.

**Comment by LeLunZ** [comment]
@abyrd also still having the problem. It also fails for smaller parts of Germany when using two osm files (of Germany) from Geofabrik with the merge function of osmium. 

So it also happens for smaller files and I think not only Germany. I come across this regularly. As I currently don't have a problem with dropping all turn restrictions, I am doing that for now. But that shouldn't be the solution :)

**Comment by abyrd** [comment]
I also patched those vertex lookups to fail cleanly with a log message when the vertex is not found. Then I re-ran the build, changing `StreetLayer#loadFromOsm()` so it calls `loadFromOsm(osm, false, false);` with removeIslands set to false. This skips the whole pruning process but the problematic vertex lookup is still hit, indicating that pruning was not the culprit. The vertex lookup fails gracefully and the build completes.

So I don't yet know why it can't find this particular from vertex, but there were already many other such cases detected for via nodes. Dropping these problematic restrictions will at least avoid an annoying failure after 20 minutes of network building.
