### ISSUE TITLE
Corrupt OSM fails silently

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#698]
If you create a new bundle in the UI, choosing or uploading a good GTFS file but a bad OSM file, the UI eventually shows the newly created bundle without the ERROR indicator that we usually see when uploading bad GTFS. The upload fails silently until you try to use the OSM in an analysis.

This is apparently because in `OSM.readPbf()`, osm-lib doesn't throw exceptions, it logs them and stops quietly. I just reproduced this problem, uploading a GTFS zip file that had been renamed to `.osm.pbf`. The frontend shows no error at all on upload, it appears that a new bundle has been successfully created. But the backend logs show: 

```
08:50:31.942 [pool-3-thread-1] INFO  com.conveyal.osmlib.OSM - OSM will be stored in a temporary file.
08:50:32.242 [pool-3-thread-1] INFO  com.conveyal.osmlib.OSM - No OSM tables exist yet, they will be created.
08:50:32.250 [pool-3-thread-1] ERROR com.conveyal.osmlib.OSM - Error occurred while parsing VEX stream.
org.openstreetmap.osmosis.osmbinary.file.FileFormatException: Unexpectedly long header 65536 bytes. Possibly corrupt file.
        at org.openstreetmap.osmosis.osmbinary.file.FileBlockHead.readHead(FileBlockHead.java:50)
        at org.openstreetmap.osmosis.osmbinary.file.FileBlock.process(FileBlock.java:130)
        at org.openstreetmap.osmosis.osmbinary.file.BlockInputStream.process(BlockInputStream.java:34)
        at com.conveyal.osmlib.PBFInput.copyTo(PBFInput.java:237)
        at com.conveyal.osmlib.OSM.readPbf(OSM.java:247)
        at com.conveyal.analysis.controllers.BundleController.lambda$create$1(BundleController.java:156)
        at com.conveyal.analysis.components.TaskScheduler$ErrorTrap.run(TaskScheduler.java:95)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

The first ERROR log entry is just wrong, it's actually trying to parse it as PBF (the log message should be changed).  

When you kick off a single point analysis, you then get "Error communicating with the server" with a NullPointerException from the worker at `TransportNetworkCache.getNetworkForScenario(TransportNetworkCache.java:111)`. The OSM processing on the worker is being done in an asynchronous task, and the exception is successfully caught by the ErrorTrap. But it should be caught farther down, in the heavyTask's catch clause.

**Comment by ansoncfit** [comment]
https://github.com/conveyal/r5/pull/713 closes.
