### ISSUE TITLE
Log noise on canceled and retried regional analyses

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#766]
Recently we saw dozens or hundreds of errors like this:
```
[production] Unknown/unauthenticated user: java.io.IOException: Stream Closed
at java.base/java.io.RandomAccessFile.seek0(Native Method)
at com.conveyal.analysis.results.GridResultWriter.writeOneOrigin(GridResultWriter.java:145)
```
This is consistent with an analysis being canceled, then the remaining batch of incoming results being dropped into the already-closed file. I think we started seeing this now because we actually clean up (delete) canceled analyses instead of leaving the temp files around. 

On an analysis that stalled and was retried, we saw a single error like this:
```
Unknown/unauthenticated user: java.io.IOException: This instance of the CsvWriter class has already been closed.
at com.csvreader.CsvWriter.checkClosed(Unknown Source)
at com.conveyal.analysis.results.CsvResultWriter.writeOneWorkResult(CsvResultWriter.java:101)
```
The reason is probably similar: a very late result caused a redelivery pass, in which some origins were handled more than once. Upon completion the file was closed and the duplicate origins could not be appended. This case (receiving results for a finished analysis) probably merits a log warning but not an exception. The first case (receiving results for a canceled analysis) is completely normal and should result in no exceptions or warnings.

**Comment by abyrd** [comment]
It's not clear how this is happening. `Broker#deleteJob` removes the job and result assemblers, then calls terminate() on the result assembler. This in turn calls terminate() on any grid and csv writers, which closes and deletes the file.

When more incoming results are received, `Broker#handleRegionalWorkResult` always checks whether the job was found and is active (not errored or complete) before calling handleMessage() on the assembler which then calls the code producing the error in this issue. Here is a more complete stack trace for that error:
```
2021-11-17 20:33:44,785 [qtp717267127-1862] ERROR c.c.a.c.e.ErrorLogger - Unknown/unauthenticated user: java.io.IOException: Stream Closed
        at java.base/java.io.RandomAccessFile.seek0(Native Method)
        at java.base/java.io.RandomAccessFile.seek(RandomAccessFile.java:591)
        at com.conveyal.analysis.results.GridResultWriter.writeOneOrigin(GridResultWriter.java:145)
        at com.conveyal.analysis.results.MultiGridResultWriter.writeOneWorkResult(MultiGridResultWriter.java:60)
        at com.conveyal.analysis.results.MultiOriginAssembler.handleMessage(MultiOriginAssembler.java:173)
        at com.conveyal.analysis.components.broker.Broker.handleRegionalWorkResult(Broker.java:467)
        at com.conveyal.analysis.controllers.BrokerController.workerPoll(BrokerController.java:353)
```

There is a (seemingly benign) race condition present in the broker method. Several threads could fetch the job and associated result assembler while it's still active, then hit a synchronization fence at assember.handleMessage() while another thread was in the process of canceling or finishing the job. The waiting threads would then enter that synchronized method while holding job and result assembler references for the already-canceled job. There is some evidence that this is what happened. A grep of analysis.log shows that in the space of less than 200 msec we got 194 such messages, each with an apparently distinct thread ID. Piping these through cut and sort, I can see that the thread IDs are unique sequential integers. This implies there were a few hundred workers polling at once, all queued up at a broker synchronization point. They were all delivering results for a canceled analysis, or perhaps one that had been redelivered. 

The question is what would have blocked the broker long enough that 200 incoming requests needed to queue up, exacerbating the race condition. Leading up to one minute before the error messages, many regional analyses were enqueued at a rate of one every minute or so, and many had just finished and stored their results. I'm not sure if this is somehow related to the errors.

As pointed out in `Broker#handleRegionalWorkResult` when the final message is received, the final results are processed and uploaded synchronously, within synchronized code on the MultiOriginAssembler. The implicit assumption here is that no more results will be coming in after this final one is received. I suppose if a job had been retried, something stalled, and workers returned results more than once, while the results were being finished and uploaded, workers might report more results and logjam waiting to use the result assembler while it was busy uploading results to S3.

Around Broker L467 we can see that the final task completing a job is only taken into account on the job (causing it and its assembler to be removed) _after_ telling the assembler to process this final message (including result processing and upload). Access to the assembler is blocked by synchronization while it finalizes and uploads these results to S3, during which any additional incoming results would be able to see the job. 

Here we have an example of a pattern we formerly had throughout the code base and have largely changed: Rather than nesting operations (method calls) conditionally and deeply, our call stack should be shorter, taking one action at a time before proceeding to subsequent processing. In this case incoming results should be processed quickly, and after they're all processed another stage should check whether this has led to any job being complete, then line up any asynchronous actions necessary, like uploading files.

On the positive side, we can see that events for each of these hundreds of exceptions were fired and handled at sub-millisecond speed, and each caused a message to be sent asynchronously to Slack. The background task execution worked nicely.

It's tempting to make `Broker#handleRegionalWorkResult` synchronized like many of the other broker methods, which would eliminate this race condition. However that method indirectly does some potentially slow things like uploading the results and starting workers, which would need to be handled after the method returns (as described above) if we synchronized it.

If we can't fully solve this, we should improve the error logging in this area, so the next time this happens we can better understand why.
