### ISSUE TITLE
Data Source Deletion of GeoJSON

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/r5#775]
I uploaded [this](https://opendata.arcgis.com/datasets/1559e31273654eb9858397861f1fdefa_10.geojson) GeoJSON file to use as a Data Source. 

When attempting to delete the data source, I saw the following error:

<img width="1498" alt="Screen Shot 2021-12-17 at 09 18 54" src="https://user-images.githubusercontent.com/776780/146473172-5555ca48-7b5c-4970-8ed7-88e1c0d92596.png">

The exact text from the client side was:

> Error deleting data source
> org.bson.codecs.configuration.CodecConfigurationException: An exception occurred when decoding using the AutomaticPojoCodec. Decoding into a 'DataSource' failed with the following exception: An exception occurred when decoding using the AutomaticPojoCodec. Decoding into a 'SpatialDataSource' failed with the following exception: Failed to decode 'SpatialDataSource'. Decoding 'issues' errored with: An exception occurred when decoding using the AutomaticPojoCodec. Decoding into a 'DataSourceValidationIssue' failed with the following exception: Cannot find a public constructor for 'DataSourceValidationIssue'. A custom Codec or PojoCodec may need to be explicitly configured and registered to handle this type. A custom Codec or PojoCodec may need to be explicitly configured and registered to handle this type. A custom Codec or PojoCodec may need to be explicitly configured and registered to handle this type.

This error was logged: 

> [production] User testing@conveyal.com of group testing accessing /api/dataSource/61bbe3fff49a7e2152fa2788: org.bson.codecs.configuration.CodecConfigurationException: An exception occurred when decoding using the AutomaticPojoCodec.
at org.bson.codecs.pojo.AutomaticPojoCodec.decode(AutomaticPojoCodec.java:40)
at com.conveyal.analysis.persistence.AnalysisCollection.findById(AnalysisCollection.java:67)

I will create a corresponding issue in the UI repo addressing the error showing in a success toast.

**Comment by abyrd** [comment]
This may just be due to a missing no-arg constructor. An annoying but frequent requirement for classes that will be deserialized.
